<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRdNbtqc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRdNbtqc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRdNbtqc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRdNbtqc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRdNbtqc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RdNbtqc',
    'container.build_id' => '5fca0a4a',
    'container.build_time' => 1589570942,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRdNbtqc');
