<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container40cNpLm\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container40cNpLm/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container40cNpLm.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container40cNpLm\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container40cNpLm\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '40cNpLm',
    'container.build_id' => 'a29b48b8',
    'container.build_time' => 1589570466,
], __DIR__.\DIRECTORY_SEPARATOR.'Container40cNpLm');
